account_id:
  - 012345678900
  - 123456789000

# If aws_region is not specified, the script will look at all regions
aws_region:
- us-east-1
- us-east-2
- us-west-1
- us-west-2

controller:
  ip: 1.1.1.1
  username: admin

defaults:
  role_name: aviatrix-role-app
  managed_tgw: True
  avtx_transit: True
  spoke_gw_size: t3.medium
  insane_mode: True
  insane_az1: "a"
  insane_az2: "b"
